sudo: required

services:
  - docker

language: c

matrix:
  include:
    - env:
    - env:
      - NDEBUG=1

before_script:
  - docker build -t buildenv .

script:
  - docker run buildenv /bin/sh -c "cd /root && make -j2 arm_sdk_install gtest_install && make all_ut_run"
