/*
 * meshcom_bc.h
 *
 *  Created on: 17.02.2011
 *      Author: cba
 */

#ifndef MESHCOM_BC_H_
#define MESHCOM_BC_H_

#include "meshcom_conn.h"
#include "settings.h"

#define MESH_SETTING_BEACON_BROADCAST_INTERVAL     _settings_list_ram[SETTINGS_MESH_BEACON_BROADCAST_INTERVAL]
#define MESH_SETTING_NODEINFO_BROADCAST_INTERVAL   _settings_list_ram[SETTINGS_MESH_NODEINFO_BROADCAST_INTERVAL]


#define MESH_BROADCAST_INTERVAL (MESH_SETTING_BEACON_BROADCAST_INTERVAL)
#define MESH_BROADCAST_INTERVAL_RETRY (MESH_SETTING_BEACON_BROADCAST_INTERVAL / 5)
#define MESH_BROADCAST_NODEINFO_INTERVAL (MESH_SETTING_NODEINFO_BROADCAST_INTERVAL)
#define MESH_BROADCAST_NODEINFO_INTERVAL_RETRY (MESH_SETTING_NODEINFO_BROADCAST_INTERVAL / 5)

#define MESH_BROADCAST_JITTER     3       // Jitter fraction (e.g. 3 eq 1/3

#define MESH_BROADCAST_SHUTUP_TIMEOUT_MAX 3600

void MESHCOM_BC_Start(void);
void MESHCOM_BC_Stop(void);
void MESHCOM_BC_Tick(void);
void MESHCOM_BC_Init(void);

MESHCOM_RESULT_T MESHCOM_SendSwitchOnOffMessage(bool b_on_or_off, RTCTIME time, MESHCOM_CB_HANDLER callback);


#endif /* MESHCOM_BC_H_ */
