
include $(dir $(lastword $(MAKEFILE_LIST)))/board-info.mk

TCHAIN_PREFIX := $(ARM_SDK_PREFIX)

CFLAGS += -DBL_ORIGIN=$(BL_ORIGIN)
CFLAGS += -DBL_SIZE=$(BL_SIZE)
CFLAGS += -DEE_ORIGIN=$(EE_ORIGIN)
CFLAGS += -DEE_SIZE=$(EE_SIZE)
CFLAGS += -DFW_ORIGIN=$(FW_ORIGIN)
CFLAGS += -DFW_SIZE=$(FW_SIZE)
CFLAGS += -DEF_ORIGIN=$(EF_ORIGIN)
CFLAGS += -DEF_SIZE=$(EF_SIZE)

CFLAGS += -DVCS_PATH=$(VCS_PATH)
CFLAGS += -DVCS_REVISION=$(VCS_REVISION)
CFLAGS += -DVCS_DATETIME="$(VCS_DATETIME)"
CFLAGS += -DVCS_DATETIME_ISO=$(VCS_DATETIME_ISO)
