/*********************************************************************************
  \file macDbg.h

  \brief Assert's code are located here.

  \author
    Atmel Corporation: http://www.atmel.com \n
    Support email: avr@atmel.com

  Copyright (c) 2008-2011, Atmel Corporation. All rights reserved.
  Licensed under Atmel's Limited License Agreement (BitCloudTM).

  \internal
    History:
      09/11/07 A. Mandychev - Created.
**********************************************************************************/
#ifndef _MACDBG_H
#define _MACDBG_H

/*********************************************************************************
 ASSERT is used for debugging wrong conditions

 Types of messages:


*********************************************************************************/

/***************************************************************
  Defines with 1 in the high-order bit should not be used as enum is signed int type
***************************************************************/
typedef enum
{
  /***********************************
    MAC & PHY section. Range 0x1000 - 0x1FFFF
  ***********************************/
  // PHY asserts' ID.
  PHYRFIRQDISPATCHER_RFINTERRUPTSUBROUTINE_0        = 0x1001,
  PHYTXFRAME_DATAREQ_0                              = 0x1002,
  PHYPIB_PHYSETPIBPARAM_0                           = 0x1003,
  PHYPIB_PHYGETPIBPARAM_0                           = 0x1004,
  PHYTXFRAME_PHYDATAREQ_0                           = 0x1005,
  PHYRXFRAME_PHYDOWNLOADFRAME_0                     = 0x1006,
  MACPHYMACENV_GETSYMBOLPEROCTET_0                  = 0x1007,
  MACPHYMACENV_GETPHYSYMBOLDURATION_0               = 0x1008,
  PHYSET_PHYSETREQ_0                                = 0x1009,
  PHYSETTRXSTATE_PHYSETTRXSTATEREQ_0                = 0x100A,
  PHYRFSPIPROTO_PHYENCRYPTBYSPI_0                   = 0x100B,
  MACPHYPIBSERVER_STORETXPOWER_0                    = 0x100C,
  PHYSET_CONVERTTXPOWER_0                           = 0x100D,
  PHYSET_PHYSETREQ_1                                = 0x100E,
  MACPHYMACENV_SETPIBATTR_0                         = 0x100F,
  MACPHYMACENV_GETPIBATTR_0                         = 0x1010,
  HALMACISRC_DISPATHRTIMEREVENT_0                   = 0x1011,
  PHYRFTXRX_CANNOT_BE_ENABLED                       = 0x1012,
  PHYRFTXRX_CANNOT_BE_DISABLED                      = 0x1013,
  PHYRFIRQDISPATCHER_WRONGSTATE_0                   = 0x1014,
  PHYRFIRQDISPATCHER_WRONGSTATE_1                   = 0x1015,
  PHYSET_PHYSETREQ_2                                = 0x1016,
  PHYANTEXTSW_CANNOT_BE_ENABLED                     = 0x1017,
  PHYANTEXTSW_CANNOT_BE_DISABLED                    = 0x1018,

  PHYRFIRQ_UNREASONABLE_IRQ                         = 0x1019,
  PHYRFIRQ_UNKNOWN_RX_STATUS                        = 0x101A,
  PHYRFIRQ_UNKNOWN_TX_STATUS                        = 0x101B,
  PHYRFIRQ_OTHER_IRQ                                = 0x101C,
  PHYRF_EXTRA_RX_FRAME                              = 0x101D,

  // MAC_HWD asserts' ID.
  MACHWDFRAMEROUTINE_MACHWDCOMPOSEFRAME_0           = 0x1021,
  MACHWDPIB_MACHWDGETPIBPARAM_0                     = 0x1022,
  MACHWDGETHANDLER_MACHWDGETREQHANDLER_0            = 0x1023,
  MACHWDRXFRAMEHANDLER_GETCURRENTCHANNEL_0          = 0x1024,
  MACHWDMANAGER_TASKHANDLER_0                       = 0x1025,
  MACHWDMANAGER_TASKHANDLER_1                       = 0x1026,
  MACHWDMANAGER_TASKHANDLER_2                       = 0x1027,
  MACHWDMANAGER_SENDREQTOHANDLER_0                  = 0x1028,
  MACHWDMANAGER_DISPATCHETASKTOHANDLER_0            = 0x1029,
  MACHWDEDHNDLR_MACHWDEDHANDLER_0                   = 0x102A,
  MACHWDEDHNDLR_MACHWDEDHANDLER_1                   = 0x102B,
  MACHWDEDHNDLR_MACHWDEDTASKHANDLER_0               = 0x102C,
  MACHWDTRXHANDLER_MACHWDTRXREQHANDLER_0            = 0x102D,
  MACHWDTRXHANDLER_TRXTASKHANDLER_0                 = 0x102E,
  MACHWDSETHANDLER_MACHWDSETREQHANDLER_0            = 0x102F,
  MACHWDSETHANDLER_MACHWDSETREQHANDLER_1            = 0x1030,
  MACHWDSETHANDLER_MACHWDSETTASKHANDLER_0           = 0x1031,
  MACHWDSETHANDLER_MACHWDSETTASKHANDLER_1           = 0x1032,
  MACHWDSETHANDLER_EXECUTESETREQ_0                  = 0x1033,
  MACHWDSETHANDLER_EXECUTEPHYSETREQ_0               = 0x1034,
  MACHWDSETHANDLER_SETRXONSTATE_0                   = 0x1035,
  MACHWDTXFRAMEHANDLER_MACHWDTXFRAMEREQHANDLER_0    = 0x1036,
  MACHWDTXFRAMEHANDLER_MACHWDTXFRAMETASKHANDLER_0   = 0x1037,
  MACHWDTXFRAMEHANDLER_EXECUTEPHYDATAREQ_0          = 0x1038,
  MACHWDTXFRAMEHANDLER_SETRXONSTATE_0               = 0x1039,
  MACHWDRESETHANDLER_MACHWDRESETREQHANDLER_0        = 0x1040,
  MACHWDTXFRAMEHANDLER_EXECUTEDATAREQ_0             = 0x1041,
  MACHWDTXFRAMEHANDLER_MACHWDTXFRAMETASKHANDLER_1   = 0x1042,
  MACHWDGETHANDLER_MACHWDGETREQHANDLER_1            = 0x1043,
  MACHWDSETHANDLER_MACHWDSETREQHANDLER_2            = 0x1044,
  MACHWDTRXCTRL_GETPHYTRXCMD_0                      = 0x1045,
  MACHWDTRXCTRL_CONVERTTRXCMDTOTRXSTATE_0           = 0x1046,
  MACHWDEDHANDLER_MACHWDEDREQHANDLER_2              = 0x1047,
  MACHWDTXFRAMEHANDLER_GETDATASTATUS_0              = 0x1048,
  MACHWDENCRYPTHANDLER_MACHWDENCRYPTREQHANDLER_0    = 0x1049,
  MACHWDENCRYPTHANDLER_MACHWDENCRYPTREQHANDLER_1    = 0x104A,
  MACHWDENCRYPTHANDLER_MACHWDENCRYPTTASKHANDLER_0   = 0x104B,
  MACHWDRNDHANDLER_MACHWDRNDREQHANDLER_0            = 0x104C,
  MACHWDRNDHANDLER_MACHWDRNDREQHANDLER_1            = 0x104D,
  MACHWDRNDHANDLER_MACHWDRNDTASKHANDLER_0           = 0x104E,
  MACHWDBATMONHANDLER_MACHWDBATMONREQHANDLER_0      = 0x104F,
  MACHWDBATMONHANDLER_MACHWDBATMONREQHANDLER_1      = 0x1050,
  MACHWDBATMONHANDLER_MACHWDBATMONTASKHANDLER_0     = 0x1051,
  MACHWDBATMONHANDLER_MACHWDBATMONTASKHANDLER_1     = 0x1052,
  MACHWDTRXCTRL_CONVERTTRXSTATETOTRXCMD_0           = 0x1053,
  MACHWDRXBUFFER_CHECKBUFFERSPACE_0                 = 0x1054,
  MACHWDRXBUFFER_COMMITRXBUFFER_0                   = 0x1055,
  MACHWDRXBUFFER_ROLLBACKRXBUFFER_0                 = 0x1056,
  MACHWDRXBUFFER_GETBUFFER_0                        = 0x1057,
  MACHWDRXBUFFER_NEXTBUFFER_0                       = 0x1058,
  MACHWDRXBUFFER_NEXTBUFFER_1                       = 0x1059,

  // MAC_HWI asserts' ID.
  MACHWIDATAHANDLER_CONVERTMACHWDDATACONFIRMTYPES_0 = 0x1080,
  MACHWIMANAGER_SENDREQTOHANDLER_0                  = 0x1083,
  MACHWIMANAGER_TASKHANDLER_0                       = 0x1084,
  MACHWIMANAGER_TASKHANDLER_1                       = 0x1085,
  MACHWISCANHANDLER_MACHWDSETCONFIRM_0              = 0x1086,
  MACHWISCANHANDLER_MACHWDSETCONFIRM_1              = 0x1087,
  MACHWISCANHANDLER_MACHWIBEACONINDICATION_0        = 0x1088,
  MACHWIASSOCIATEHANDLER_MACHWDSETCONFIRM_0         = 0x1089,
  MACHWIASSOCIATEHANDLER_MACHWDSETTRXSTATECONFIRM_0 = 0x108A,
  MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_0        = 0x108B,
  MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_1        = 0x108C,
  MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_2        = 0x108D,
  MACHWIASSOCIATEHANDLER_ASSOCIATETIMERFIRED_0      = 0x108E,
  MACHWITRANSACTIONQUEUE_GETDSTADDRINFO_0           = 0x108F,
  MACHWITRANSACTIONQUEUE_GETDSTADDRINFO_1           = 0x1090,
  MACHWITRANSACTIONHANDLER_MACHWDDATACONFIRM_0      = 0x1091,
  MACHWITRANSACTIONHANDLER_MACHWDDATACONFIRM_1      = 0x1092,
  MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_0   = 0x1093,
  MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_1   = 0x1094,
  MACHWITRANSACTIONQUEUE_GETACTIVATEDTRANSACTION_0  = 0x1095,
  MACHWISTARTHANDLER_MACHWDSETCONFIRM_0             = 0x1096,
  MACHWISTARTHANDLER_MACHWDSETCONFIRM_1             = 0x1097,
  MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_0      = 0x1098,
  MACHWIPOLLHANDLER_MACHWDDATACONFIRM_0             = 0x1099,
  MACHWIPOLLHANDLER_ISITREQUESTEDDATA_0             = 0x109A,
  MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_1      = 0x109B,
  MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_2      = 0x109C,
  MACHWISCANHANDLER_MACHWISCANREQHANDLER_0          = 0x109D,
  MACHWISCANHANDLER_MACHWDSETCONFIRM_2              = 0x109E,
  MACHWISCANHANDLER_MACHWDSETCONFIRM_3              = 0x109F,
  MACHWISCANHANDLER_MACHWDSETCONFIRM_4              = 0x10A0,
  MACHWIDISASSOCIATEHANDLER_MACHWDDATACONFIRM_0     = 0x10A1,
  MACHWISWITCHRXCTRL_SWITCHRXONWHENIDLE_0           = 0x10A2,
  MACHWIMANAGER_MACHWISENDCONFTOUPPERLAYER_0        = 0x10A3,
  MACHWISETHANDLER_MACHWDSETCONFIRM_0               = 0x10A4,
  MACHWIGETHANDLER_MACHWDGETCONFIRM_0               = 0x10A5,
  MACHWISTARTHANDLER_MACHWISTARTREQHANDLER_0        = 0x10A6,
  MACHWIRESETHANDLER_MACHWDSETCONFIRM_0             = 0x10A7,
  MACHWIDISASSOCIATEHANDLER_MACHWDSETCONFIRM_0      = 0x10A8,
  MACHWISTARTHANDLER_MACHWDDATACONFIRM_0            = 0x10A9,
  MACHWIENCRYPTHANDLER_MACHWISETKEYREQ_0            = 0x10AA,
  MACHWIENCRYPTHANDLER_MACHWDENCRYPTCONF_0          = 0x10AB,
  MACHWIENCRYPTHANDLER_MACHWIENCRYPTREQHANDLER_0    = 0x10AC,
  MACHWIASSOCIATEHANDLER_SETHANDLING_0              = 0x10AD,
  MACHWIASSOCIATEHANDLER_MACHWDSETCONFIRM_1         = 0x10AE,
  MACHWIASSOCIATEHANDLER_ASSOCIATETIMERFIRED_1      = 0x10AF,
  MACHWIDISASSOCIATEHANDLER_SETHANDLING_0           = 0x10B0,
  MACHWIRESETHANDLER_SETHANDLING_0                  = 0x10B1,
  MACHWISCANHANDLER_SETHANDLING_0                   = 0x10B2,
  MACHWISCANHANDLER_MACHWDEDCONFIRM_0               = 0x10B3,
  MACHWISCANHANDLER_TRXSTATEHANDLING_0              = 0x10B4,
  MACHWISTARTHANDLER_MACHWDSETCONFIRM_2             = 0x10B5,
  MACHWISWITCHRXCTRL_SWITCHRXONWHENIDLE_1           = 0x10B6,
  MACHWISTARTHANDLER_SETHANDLING_0                  = 0x10B7,
  MACHWISCANHANDLERC_MACHWDEDCONFIRM_0              = 0x10B8,
  MACHWISCANHANDLERC_TRXSTATEHANDLING_0             = 0X10b9,
  PHYRFIRQDISPATCHER_RFINTERRUPTSUBROUTINE_1        = 0x10ba,
  MACHWITRANSACTIONQUEUE_TESTANDKICKQUEUETRANS_0    = 0x10bb,
  MACHWIMANAGER_PROCEEDPOSTPONEDACTIONS_0           = 0x10bc,
  MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_2   = 0x10bd,
  MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_3   = 0x10be,
  MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_4   = 0x10bf,
  MACHWIBANNODE_MACBANNODE0                         = 0x10c0,

  MACHWD_RX_RELEASE_BUFFER_LIMIT                    = 0x1ff9,
  MACHWD_POST_TASK_TIME_LIMIT                       = 0x1ffa,
  MACHWD_RESET_TIME_LIMIT                           = 0x1ffb,
  MACHWD_SETHANDLER_ID_1_TIME_LIMIT                 = 0x1ffc,
  MACHWD_SETHANDLER_ID_2_TIME_LIMIT                 = 0x1ffd,
  MACHWD_SETHANDLER_ID_3_TIME_LIMIT                 = 0x1ffe,
  MACHWD_SETHANDLER_ID_4_TIME_LIMIT                 = 0x1fff
} MacDbgCode_t;

typedef enum
{
  LOG_MAC_MAC_DATA_REQ,
  LOG_MAC_SEND_REQ_TO_HANDLER,
  LOG_MAC_SEND_CONF_TO_UPPER,
  LOG_MAC_SEND_TRANSAC_EVENT,
  LOG_MAC_SEND_TRANSAC_EVENT2
} MacLogCodeId_t;

#endif /* _MACDBG_H */

//end of macDbg.h

