/* local_texts.h
 *
 * Note: This file has been automatically generated from system/local_texts.txt by tools/generateLocalTexts.pl
 *       Any changes made to this file will get lost!
 * Text encoded as UTF-8.
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef LOCAL_TEXTS_H
#define LOCAL_TEXTS_H

#include "languages.h"

    typedef enum settings_texts_e {
        SET_NAME_none,
        SET_NAME_system_systemtype,
        SET_NAME_system_hardwaretype,
        SET_NAME_start_mesh_mesh,
        SET_NAME_autoconfig,
        SET_NAME_nodetype,
        SET_NAME_channelpage,
        SET_NAME_channelmask,
        SET_NAME_panid,
        SET_NAME_nwk_addr,
        SET_NAME_broadcast_interval,
        SET_NAME_tx_power,
        SET_NAME_selected_profile,
        SET_NAME_modbus_control,
        SET_NAME_use_light_sensor,
        SET_NAME_active_mode,
        SET_NAME_avg_calc_method,
        SET_NAME_avg_calc_method_gl,
        SET_NAME_min_gloom_tolerance,
        SET_NAME_min_num_reliable_cl,
        SET_NAME_timeout_nw_gloom,
        SET_NAME_reduce_light_output,
        SET_NAME_sensor_type,
        SET_NAME_cluster_id,
        SET_NAME_cluster_mask,
        SET_NAME_hysteresis,
        SET_NAME_use_relais_1,
        SET_NAME_warn_sensors,
        SET_NAME_warn_visibility,
        SET_NAME_warn_gps,
        SET_NAME_warn_mesh,
        SET_NAME_ema_factor,
        SET_NAME_tol_factor,
        SET_NAME_min_num_ext_gl,
        SET_NAME_led_on_off_mode,
        SET_NAME_max_repeat_on_off,
        SET_NAME_timeout_last_keep_on_msg,
        SET_NAME_min_num_rec_val_filtering,
        SET_NAME_mesh_fw_tx,
        SET_NAME_mesh_fw_tx_bcoff,
        SET_DESC_none,
        SET_DESC_system_systemtype,
        SET_DESC_system_hardwaretype,
        SET_DESC_start_mesh_mesh,
        SET_DESC_autoconfig,
        SET_DESC_nodetype,
        SET_DESC_channelpage,
        SET_DESC_channelmask,
        SET_DESC_panid,
        SET_DESC_nwk_addr,
        SET_DESC_broadcast_interval,
        SET_DESC_tx_power,
        SET_DESC_selected_profile,
        SET_DESC_modbus_control,
        SET_DESC_use_light_sensor,
        SET_DESC_active_mode,
        SET_DESC_avg_calc_method,
        SET_DESC_avg_calc_method_gl,
        SET_DESC_min_gloom_tolerance,
        SET_DESC_min_num_reliable_cl,
        SET_DESC_timeout_nw_gloom,
        SET_DESC_reduce_light_output,
        SET_DESC_sensor_type,
        SET_DESC_cluster_id,
        SET_DESC_cluster_mask,
        SET_DESC_hysteresis,
        SET_DESC_use_relais_1,
        SET_DESC_warn_sensors,
        SET_DESC_warn_visibility,
        SET_DESC_warn_gps,
        SET_DESC_warn_mesh,
        SET_DESC_ema_factor,
        SET_DESC_tol_factor,
        SET_DESC_min_num_ext_gl,
        SET_DESC_led_on_off_mode,
        SET_DESC_max_repeat_on_off,
        SET_DESC_timeout_last_keep_on_msg,
        SET_DESC_min_num_rec_val_filtering,
        SET_DESC_mesh_fw_tx,
        SET_DESC_mesh_fw_tx_bcoff,
        SET_NOTE_none,
        SET_NOTE_system_systemtype,
        SET_NOTE_system_hardwaretype,
        SET_NOTE_start_mesh_mesh,
        SET_NOTE_autoconfig,
        SET_NOTE_nodetype,
        SET_NOTE_channelpage,
        SET_NOTE_channelmask,
        SET_NOTE_panid,
        SET_NOTE_nwk_addr,
        SET_NOTE_broadcast_interval,
        SET_NOTE_tx_power,
        SET_NOTE_selected_profile,
        SET_NOTE_modbus_control,
        SET_NOTE_use_light_sensor,
        SET_NOTE_active_mode,
        SET_NOTE_avg_calc_method,
        SET_NOTE_avg_calc_method_gl,
        SET_NOTE_min_gloom_tolerance,
        SET_NOTE_min_num_reliable_cl,
        SET_NOTE_timeout_nw_gloom,
        SET_NOTE_reduce_light_output,
        SET_NOTE_sensor_type,
        SET_NOTE_cluster_id,
        SET_NOTE_cluster_mask,
        SET_NOTE_hysteresis,
        SET_NOTE_use_relais_1,
        SET_NOTE_warn_sensors,
        SET_NOTE_warn_visibility,
        SET_NOTE_warn_gps,
        SET_NOTE_warn_mesh,
        SET_NOTE_ema_factor,
        SET_NOTE_tol_factor,
        SET_NOTE_min_num_ext_gl,
        SET_NOTE_led_on_off_mode,
        SET_NOTE_max_repeat_on_off,
        SET_NOTE_timeout_last_keep_on_msg,
        SET_NOTE_min_num_rec_val_filtering,
        SET_NOTE_mesh_fw_tx,
        SET_NOTE_mesh_fw_tx_bcoff,
        SETTINGS_TEXTS_COUNT
    }
    SETTINGS_TEXTS_E;

    const char *getLocalText_settings_texts(SETTINGS_TEXTS_E Text, LANGUAGE_E Language);

    typedef enum status_texts_e {
        STAT_NAME_time,
        STAT_NAME_uptime,
        STAT_NAME_logentries,
        STAT_NAME_systemtype,
        STAT_NAME_led_fail_bm,
        STAT_NAME_led_power_rel,
        STAT_NAME_led_power_abs,
        STAT_NAME_timemeter,
        STAT_NAME_sensor_avail_bm,
        STAT_NAME_temperature,
        STAT_NAME_light,
        STAT_NAME_visibility,
        STAT_NAME_gps_status,
        STAT_NAME_gps_num_sat_fix,
        STAT_NAME_gps_sat_id_list,
        STAT_NAME_gps_fixtype,
        STAT_NAME_gps_latitude,
        STAT_NAME_gps_longitude,
        STAT_NAME_gps_altitude,
        STAT_NAME_network_client_count,
        STAT_NAME_network_bc_msgs_received,
        STAT_NAME_network_gloom_network_avg,
        STAT_NAME_firmware_hw_id,
        STAT_NAME_firmware_hw_revision,
        STAT_NAME_firmware_sw_version_major,
        STAT_NAME_firmware_sw_version_minor,
        STAT_NAME_firmware_size,
        STAT_NAME_firmware_checksum,
        STAT_NAME_firmware_validated,
        STAT_NAME_firmware_retry_bits,
        STAT_DESC_time,
        STAT_DESC_uptime,
        STAT_DESC_logentries,
        STAT_DESC_systemtype,
        STAT_DESC_led_fail_bm,
        STAT_DESC_led_power_rel,
        STAT_DESC_led_power_abs,
        STAT_DESC_timemeter,
        STAT_DESC_sensor_avail_bm,
        STAT_DESC_temperature,
        STAT_DESC_light,
        STAT_DESC_visibility,
        STAT_DESC_gps_status,
        STAT_DESC_gps_num_sat_fix,
        STAT_DESC_gps_sat_id_list,
        STAT_DESC_gps_fixtype,
        STAT_DESC_gps_latitude,
        STAT_DESC_gps_longitude,
        STAT_DESC_gps_altitude,
        STAT_DESC_network_client_count,
        STAT_DESC_network_bc_msgs_received,
        STAT_DESC_network_gloom_network_avg,
        STAT_DESC_firmware_hw_id,
        STAT_DESC_firmware_hw_revision,
        STAT_DESC_firmware_sw_version_major,
        STAT_DESC_firmware_sw_version_minor,
        STAT_DESC_firmware_size,
        STAT_DESC_firmware_checksum,
        STAT_DESC_firmware_validated,
        STAT_DESC_firmware_retry_bits,
        STAT_HINT_time,
        STAT_HINT_uptime,
        STAT_HINT_logentries,
        STAT_HINT_systemtype,
        STAT_HINT_led_fail_bm,
        STAT_HINT_led_power_rel,
        STAT_HINT_led_power_abs,
        STAT_HINT_timemeter,
        STAT_HINT_sensor_avail_bm,
        STAT_HINT_temperature,
        STAT_HINT_light,
        STAT_HINT_visibility,
        STAT_HINT_gps_status,
        STAT_HINT_gps_num_sat_fix,
        STAT_HINT_gps_sat_id_list,
        STAT_HINT_gps_fixtype,
        STAT_HINT_gps_latitude,
        STAT_HINT_gps_longitude,
        STAT_HINT_gps_altitude,
        STAT_HINT_network_client_count,
        STAT_HINT_network_bc_msgs_received,
        STAT_HINT_network_gloom_network_avg,
        STAT_HINT_firmware_hw_id,
        STAT_HINT_firmware_hw_revision,
        STAT_HINT_firmware_sw_version_major,
        STAT_HINT_firmware_sw_version_minor,
        STAT_HINT_firmware_size,
        STAT_HINT_firmware_checksum,
        STAT_HINT_firmware_validated,
        STAT_HINT_firmware_retry_bits,
        STATUS_TEXTS_COUNT
    } STATUS_TEXTS_E;

    const char *getLocalText_status_texts(STATUS_TEXTS_E Text, LANGUAGE_E Language);



#endif //LOCAL_TEXTS_H

#ifdef __cplusplus
}
#endif


