#ifndef FACTORYTEST_H
#define FACTORYTEST_H


#define FACTORYTEST_RELAIS_CYCLE_MAX        8
#define FACTORYTEST_RELAIS_CYCLE_TIMEOUT    (FACTORYTEST_SHOW_INTERVAL / 100) * 2 // timeout in 100ms

#define FACTORYTEST_FLATON_TIMEOUT      4  // 4 seconds

#define FACTORYTEST_TEST_LED_INTERVAL   2000  // 2000 ms

#define FACTORYTEST_CHANGE_LED_INTERVAL 2000  // 2000 ms, must be smaller than FACTORYTEST_FLATON_TIMEOUT
#define FACTORYTEST_SHOW_INTERVAL 800  // 800 ms

#define FACTORYTEST_LEDPOWER_WHITE      10000
#define FACTORYTEST_LEDPOWER_RED        10000

#define FACTORYTEST_NUM_LOG_ENTRIES   10

typedef enum
{
    FACTORYTEST_LED_NONE,
    FACTORYTEST_LED_WHITE,
    FACTORYTEST_LED_RED,
} FACTORYTEST_LED_T;

bool FACTORYTEST_Run(void);

#endif
