/*
 * svwire.h
 *
 * (c) Quantec Networks GmbH
 *
 *  Created on: 13.02.2013
 *      Author: DHA
 *
 * Purpose:
 * Include type definitions from svwire
 *
 */

#ifndef SVWIRE_H
#define SVWIRE_H

typedef enum
{
    SVWIRE_UPS_CONTROL_UPS_STATUS_UNKNOWN = 0,
    SVWIRE_UPS_CONTROL_UPS_STATUS_MAINS,
    SVWIRE_UPS_CONTROL_UPS_STATUS_BUFFERING,
    SVWIRE_UPS_CONTROL_UPS_STATUS_COUNT,
} SVWIRE_UPS_CONTROL_UPS_STATUS_T;

typedef enum
{
    SVWIRE_UPS_CONTROL_BATTERY_STATUS_NOK = -1,
    SVWIRE_UPS_CONTROL_BATTERY_STATUS_UNKNOWN = 0,
    SVWIRE_UPS_CONTROL_BATTERY_STATUS_OK,
    SVWIRE_UPS_CONTROL_BATTERY_STATUS_COUNT,
} SVWIRE_UPS_CONTROL_BATTERY_STATUS_T;

typedef enum
{
    SVWIRE_DETECTOR_TEMPERATURE_RATING_UNDER_TEMPERATURE = -3,
    SVWIRE_DETECTOR_TEMPERATURE_RATING_OVER_TEMPERATURE = -2,
    SVWIRE_DETECTOR_TEMPERATURE_RATING_ERROR = -1,
    SVWIRE_DETECTOR_TEMPERATURE_RATING_INIT = 0,
    SVWIRE_DETECTOR_TEMPERATURE_RATING_OK
} SVWIRE_DETECTOR_TEMPERATURE_RATING_T;

typedef enum
{
    SVWIRE_DETECTOR_VOLTAGE_RATING_UNDER_VOLTAGE = -2,
    SVWIRE_DETECTOR_VOLTAGE_RATING_OVER_VOLTAGE = -1,
    SVWIRE_DETECTOR_VOLTAGE_RATING_INIT = 0,
    SVWIRE_DETECTOR_VOLTAGE_RATING_OK
} SVWIRE_DETECTOR_VOLTAGE_RATING_T;

typedef enum
{
    SVWIRE_DETECTOR_TEMPERATURE_FUSE_RATING_BROKEN = -1,
    SVWIRE_DETECTOR_TEMPERATURE_FUSE_RATING_INIT = 0,
    SVWIRE_DETECTOR_TEMPERATURE_FUSE_RATING_OK
} SVWIRE_DETECTOR_TEMPERATURE_FUSE_RATING_T;

typedef enum
{
    SVWIRE_DETECTOR_SERVICE_STATUS_ERROR = -2,
    SVWIRE_DETECTOR_SERVICE_STATUS_REPLACE = -1,
    SVWIRE_DETECTOR_SERVICE_STATUS_INIT = 0,
    SVWIRE_DETECTOR_SERVICE_STATUS_OK
} SVWIRE_DETECTOR_SERVICE_STATUS_T;

typedef enum
{
    SVWIRE_BATTERY_MANAGER_BATTERY_TIMEMETER_STATUS_INVALID = -2,
    SVWIRE_BATTERY_MANAGER_BATTERY_TIMEMETER_STATUS_FAILED = -1,
    SVWIRE_BATTERY_MANAGER_BATTERY_TIMEMETER_STATUS_INIT = 0,
    SVWIRE_BATTERY_MANAGER_BATTERY_TIMEMETER_STATUS_VALID = 1
} SVWIRE_BATTERY_MANAGER_BATTERY_TIMEMETER_STATUS_T;

#endif
