/*
 * visibility_vaisala_pwd20.h
 *
 *  Created on: 18.08.2011
 *      Author: cba
 */

#ifndef VISIBILITY_VAISALA_PWD20_H_
#define VISIBILITY_VAISALA_PWD20_H_

#include "uart.h"

#define VISI_MSG_POS_PAYLOAD    7
#define VISI_MSG_ID_0   0

#define VISI_RECV_BUFFER_SIZE 50

/*
#define VISI_MSG_STATUS_HARDWAREERROR       0x01
#define VISI_MSG_STATUS_HARDWAREWARNING     0x02
#define VISI_MSG_STATUS_BACKSCATTERALARM    0x03
#define VISI_MSG_STATUS_BACKSCATTERWARNING  0x04
#define VISI_MSG_STATUS_VISIBILITYALARM1    0x10
#define VISI_MSG_STATUS_VISIBILITYALARM2    0x20
#define VISI_MSG_STATUS_VISIBILITYALARM3    0x30
*/


#define VISIBILITY_UART_CHANNEL            UART_CHANNEL_4
#define VISIBILITY_UART_SEND(c)            UART4_PutChar(c)

#define VISIBILITY_BAUDRATE                         9600

#define VISIBILITY_TASK_DELAY_TIME                  100    // 100ms
#define VISIBILITY_TASK_DELAY_TIME_NO_VISIBILITY    10000  // 10s

enum visibility_states
{
    VISI_STATE_INIT,
    VISI_STATE_ACQUIRE,
    VISI_STATE_WAIT_ANSWER,
    VISI_STATE_IDLE,
    VISI_STATE_FAILED
};

bool VISIBILITY_VAISALA_PWD20_Acquire(Visibility_Data_In_Callback_t *pFunc);
void VISIBILITY_VAISALA_PWD20_Init(void);
void VISIBILITY_VAISALA_PWD20_DeInit(void);


#endif /* VISIBILITY_VAISALA_PWD20_H_ */
