/*
 * led_compensation.h
 *
 *  Created on: 17.06.2010
 *      Author: Carsten Bartels
 */

#ifndef LED_COMPENSATION_H_
#define LED_COMPENSATION_H_

#include "dim.h"

typedef enum
{
    LED_COMPENSATION_LED_PHLATLIGHT_SST_90_WHITE,
    LED_COMPENSATION_LED_LUXEON_LXML_PH01_REDORANGE,
    LED_COMPENSATION_COUNT
} LED_COMPENSATION_LED_TYPE_T;

#define LED_COMPENSATION_WHITE_LED_AVG_VOLTAGE  44400  // 44,4V average LED voltage
#define LED_COMPENSATION_RED_LED_AVG_VOLTAGE    54000  // todo calculate 52V maximum LED voltage (nominal voltage 46,8V)

#define LED_COMPENSATION_NO_COMPENSATION_FACTOR 100  // 100%
#define LED_COMPENSATION_WHITE_DEFAULT_JUNCTION_TEMPERATURE     120  // 120°C
#define LED_COMPENSATION_TIMEMETER_COMPENSATION_MIN_TEMPERATURE 80  // 80 °C
#define LED_COMPENSATION_TIMEMETER_REF_TEMPERATURE              80  // 80 °C
#define LED_COMPENSATION_AGING_SLOPE_80                         149  // 1.49 E-6
#define LED_COMPENSATION_AGING_SLOPE_120                        244  // 2.44 E-6
#define LED_COMPENSATION_TEMPERATURE_DIFFERENCE                 40  // 120 - 80

#define LED_COMPENSATION_AGING_FACTOR

#define LED_COMPENSATION_LED_CURRENT                6200  // 6200 mA
#define LED_COMPENSATION_NUMBER_LEDS_PER_CIRCUIT    12
#define LED_COMPENSATION_SST_90_WHITE_RTHJB         2  // K/W

uint16_t LED_COMPENSATION_GetCompensation(DIM_LED_T led);
uint16_t LED_COMPENSATION_GetTimemeterCompensation(DIM_LED_T led);

#endif /* LED_COMPENSATION_H_ */
