/*
 * memtest.h
 *
 * (c) Quantec Networks GmbH
 *
 *  Created on: 14.07.2011
 *      Author: DHA
 *
 * Purpose:
 * Check external fram and flash at first startup.
 *
 */

#ifndef MEMTEST_H_
#define MEMTEST_H_

#define MEMTEST_FRAM_NUM_ITERATIONS			3
#define MEMTEST_FLASH_NUM_ITERATIONS			2
#define MEMTEST_FLASH_NUM_BYTES_PER_CYCLE	64
#define MEMTEST_FLASH_NUM_CYCLES			20
#define MEMTEST_FLASH_NUM_BYTES_PATTERN		8
#define MEMTEST_FLASH_NUM_PATTERNS			(MEMTEST_FLASH_NUM_BYTES_PER_CYCLE / MEMTEST_FLASH_NUM_BYTES_PATTERN)
#define MEMTEST_FLASH_TEST_END_ADDRESS		(MEMTEST_FLASH_NUM_BYTES_PER_CYCLE * MEMTEST_FLASH_NUM_CYCLES)
#define MEMTEST_FLASH_VALUE_CLEARED			0xFFFFFFFFFFFFFFFFULL

typedef enum
{
	MEMTEST_RESULT_ERROR_SUBTEST_4 = -7,
	MEMTEST_RESULT_ERROR_SUBTEST_3 = -6,
	MEMTEST_RESULT_ERROR_SUBTEST_2 = -5,
	MEMTEST_RESULT_ERROR_SUBTEST_1 = -4,
	MEMTEST_RESULT_ERROR_SPI_WRITE = -3,
	MEMTEST_RESULT_ERROR_SPI_READ = -2,
	MEMTEST_RESULT_ERROR_UNKNOWN = -1,
	MEMTEST_RESULT_UNDEFINED = 0,
	MEMTEST_RESULT_OK = 1
}MEMTEST_RESULT_T;

MEMTEST_RESULT_T MEMTEST_EXT_FRAM(void);
MEMTEST_RESULT_T MEMTEST_EXT_FLASH(void);

#endif /* MEMTEST_H_ */
